# 例外(Exception)
- プログラムの実行中に発生した「例外的な問題」「エラーが起きてプログラムの実行を続けることができなくなった状態」<br>
  - 例外が発生した時点でプログラムの実行は終了してしまう。そこで意図的にそのエラーを補足し、プログラムを続行させる。：堅牢で読みやすいコードができる<br>
  - 「これはプログラムが続行できない異常事態」として例外を意図的に発生させる事もできる<br><br>

```
puts "---数値を入力してください---"
i = gets.to_i

begin
  # 例外が起きうる処理
  puts 10 / i
rescue => ex
  # 例外が発生した場合の処理
  puts "error!"
  # エラー内容のメッセージ
  puts ex.message
  puts ex.class
ensure
  # 例外が発生しても、しなくても最後に実行したい処理
  puts "end"
end

# 0を入力
error!
divided by 0
ZeroDivisionError
end
```

<br>

```
module Greeting
  def morning
    "morning"
  end
end
greeting = Greeting.new
```
<br>
上のコードをirbで実行<br>
<br>

```
irb(main):001:0> module Greeting
irb(main):002:1> def morning
irb(main):003:2> "morning"
irb(main):004:2> end
irb(main):005:1> end
=> :morning
irb(main):006:0> greeting = Greeting.new
Traceback (most recent call last):
        4: from /Users/~/.rbenv/versions/2.6.5/bin/irb:23:in `<main>'
        3: from /Users/~/.rbenv/versions/2.6.5/bin/irb:23:in `load'
        2: from /Users/~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        1: from (irb):6
NoMethodError (undefined method `new' for Greeting:Module)
```
<br>
最後の3行が発生した例外に関する詳細情報。<br>
最後の２行は例外が発生するまでのプログラムの実行過程：バックトレース、もしくはスタックトレース。上の行ほど例外の発生箇所に近く、下になるほど例外の発生箇所から離れている。<br>
  ・NoMethodError (undefined method `new' for Greeting:Module)→モジュールはインスタンスを作ることができないので「greeting = Greeting.new」実行直後に例外（エラー）が発生<br>
  ・irb:11→irbプログラムの11行目が実行され<br>
  ・(irb):6→irb内の6行目で例外が発生した<br><br>
  
```
puts "Start."
module Greeting
  def morning
    "morning"
  end
end

greeting = Greeting.new
puts "End."
# Startは出力されるが、End.は出力されない
```

<br>

```
puts "Start"
module Greeting
  def morning
    "morning"
  end
end

# 例外処理を組み込んで例外に対処する
begin
  greeting = Greeting.new
rescue
  puts "例外が発生したが、このまま続行"
end

# 例外処理を組み込んだので最後まで実行可能
puts "End"

# 下記のように出力される
Start.
例外が発生したが、このまま続行
End.
```

<br><br>

※予期できない箇所(begin〜rescueで囲まれていない場合)で例外が発生した場合は、そこで処理を中断してメソッドの呼び出しを1つずつ戻る。<br>
メソッド呼び出しを戻る途中にその例外を捕捉するコードがあれば、そこから処理を続行する。<br>
  →捕捉されなかった場合は、プログラム全体がそこで異常終了する<br><br>
  
※例外処理は、適切なシーン以外で使うとプログラムに余計な混乱を招いてしまう。<br>
- 安易にrescueを使わない<br>
  →処理中のデータ構造が崩れたりし、別の問題を引き起こす恐れがある。異常事態が発生したのであればプログラムの実行を即座に中止（rescueしない）、例外の原因を調査し、適切な対応（不具合の修正や機能追加など）を行ってから、プログラムを再度実行する。<br>
- rescueしたら情報を残す<br>
  →例外が発生しても原則rescueしないのが原則だが、状況によってはrescueすべきケースも存在する。その場合、発生した例外の『クラス名』『エラーメッセージ』『バックトレース』の３つはログやターミナルに出力する。<br>
- 例外処理の対象範囲と対象クラスを極力絞り込む<br>
- 例外処理よりも条件分岐を使う<br>
  →begin〜endを使うよりも条件分岐を使った方が可読性やパフォーマンスの面で有利。例外処理を書く前にAPIドキュメントを読んで、問題の有無を事前に確認できるメソッドが用意されていないかチェックする。<br>
- 予期しない条件は異常終了させる